<aside class="fixed inset-y-0 left-0 z-40 hidden w-[17.5rem] flex-col border-r border-slate-200/80 bg-white/85 px-6 py-7 text-slate-600 backdrop-blur-xl lg:flex">
    <a href="{{ route('checkpoint-user.index') }}" class="group mb-12 flex items-center gap-3">
        <span class="grid h-10 w-10 place-items-center rounded-xl bg-sky-500 text-xl text-white shadow-[0_8px_20px_rgba(14,165,233,.18)] transition-transform duration-300 ease-[cubic-bezier(.22,1,.36,1)] group-hover:scale-105"><i class="ri-calendar-check-line"></i></span>
        <span><span class="block text-[10px] font-semibold uppercase tracking-[.18em] text-slate-400">Workspace</span><strong class="text-[15px] tracking-tight text-slate-900">Check Point</strong></span>
    </a>
    <p class="mb-3 px-3 text-[10px] font-semibold uppercase tracking-[.16em] text-slate-400">Menu</p>
    <nav class="space-y-1">
        <a href="{{ route('dashboard.index') }}" class="group flex items-center gap-3 rounded-lg px-3 py-2.5 text-[13px] font-medium transition duration-300 ease-[cubic-bezier(.22,1,.36,1)] hover:bg-slate-50 hover:text-sky-600 {{ request()->routeIs('dashboard.*') ? 'bg-sky-50 font-semibold text-sky-700' : '' }}"><i class="ri-dashboard-line text-lg text-slate-400 transition-transform duration-300 group-hover:translate-x-0.5 group-hover:text-sky-500"></i>Dashboard</a>
        <a href="{{ route('checkpoint-user.index') }}" class="group flex items-center gap-3 rounded-lg px-3 py-2.5 text-[13px] font-medium transition duration-300 ease-[cubic-bezier(.22,1,.36,1)] hover:bg-slate-50 hover:text-sky-600 {{ request()->routeIs('checkpoint-user.index') ? 'bg-sky-50 font-semibold text-sky-700' : '' }}"><i class="ri-calendar-2-line text-lg text-slate-400 transition-transform duration-300 group-hover:translate-x-0.5 group-hover:text-sky-500"></i>Kalender</a>
        <a href="{{ route('checkpoint-user.create') }}" class="group flex items-center gap-3 rounded-lg px-3 py-2.5 text-[13px] font-medium transition duration-300 ease-[cubic-bezier(.22,1,.36,1)] hover:bg-slate-50 hover:text-sky-600 {{ request()->routeIs('checkpoint-user.create') ? 'bg-sky-50 font-semibold text-sky-700' : '' }}"><i class="ri-add-line text-lg text-slate-400 transition-transform duration-300 group-hover:translate-x-0.5 group-hover:text-sky-500"></i>Tambah pekerjaan</a>
        <a href="{{ route('slip-gaji.index') }}" class="group flex items-center gap-3 rounded-lg px-3 py-2.5 text-[13px] font-medium transition duration-300 ease-[cubic-bezier(.22,1,.36,1)] hover:bg-slate-50 hover:text-sky-600 {{ request()->routeIs('slip-gaji.*') ? 'bg-sky-50 font-semibold text-sky-700' : '' }}"><i class="ri-file-list-3-line text-lg text-slate-400 transition-transform duration-300 group-hover:translate-x-0.5 group-hover:text-sky-500"></i>Slip gaji</a>
    </nav>
    <div class="mt-auto">
        <div class="mb-4 border-t border-slate-200/80 pt-5 text-xs leading-5 text-slate-400"><i class="ri-information-line mr-1 text-sky-500"></i>Pilih tanggal untuk mengisi pekerjaan.</div>
        <form method="POST" action="{{ route('logout') }}">@csrf<button type="submit" class="group flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-[13px] font-medium text-slate-500 transition duration-300 ease-[cubic-bezier(.22,1,.36,1)] hover:bg-rose-50 hover:text-rose-600"><i class="ri-logout-box-r-line text-lg transition-transform duration-300 group-hover:translate-x-0.5"></i>Logout</button></form>
    </div>
</aside>
<div class="fixed inset-x-0 top-0 z-30 flex items-center justify-between border-b border-slate-200/80 bg-white/90 px-4 py-3 text-slate-800 shadow-sm backdrop-blur-xl lg:hidden"><div class="flex items-center gap-2 text-sm font-semibold"><i class="ri-calendar-check-line text-lg text-sky-500"></i>Check Point</div><a href="{{ route('checkpoint-user.index') }}" class="rounded-lg bg-sky-500 px-3 py-1.5 text-xs font-semibold text-white shadow-sm transition duration-300 ease-[cubic-bezier(.22,1,.36,1)] active:scale-[.98]">Kalender</a></div>
